version: '3.4'

services:
  apigeteway:
    image: ${DOCKER_REGISTRY-}apigeteway
    build:
      context: .
      dockerfile: ApiGeteway/Dockerfile
    ports:
    - 9004:8080
    - 9005:8081
    depends_on:
    - usermanagement.db
    - productmanagement.db
    - usermanagement.api
    - productmanagement.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_HTTPS_PORT=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=mypass123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
  productmanagement.db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 8002:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=myStong_Password123%
  productmanagement.api:
    image: ${DOCKER_REGISTRY-}productmanagementapi
    build:
      context: .
      dockerfile: src/ProductManagement.API/Dockerfile
    ports:
      - 9000:8080
      - 9001:8081
    depends_on:
      - productmanagement.db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_HTTPS_PORT=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=mypass123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - Docker_ProductDb_ConnectionString=Server=productmanagement.db,1433;Database=product_management;User Id=sa;Password=myStong_Password123%;TrustServerCertificate=True;
    volumes:
      - ~/.aspnet/https:/https:ro
  usermanagement.db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
    - 8003:1433
    environment:
    - ACCEPT_EULA=Y
    - MSSQL_SA_PASSWORD=myStong_Password1234%
  usermanagement.api:
    image: ${DOCKER_REGISTRY-}usermanagementapi
    build:
      context: .
      dockerfile: src/UserManagement.API/Dockerfile
    ports:
    - 9002:8080
    - 9003:8081
    depends_on:
    - usermanagement.db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_HTTPS_PORT=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=mypass123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - Docker_UserDb_ConnectionString=Server=usermanagement.db,1433;Database=user_management;User Id=sa;Password=myStong_Password1234%;TrustServerCertificate=True;
    volumes:
      - ~/.aspnet/https:/https:ro
  
