version: '3.4'

services:
  apigeteway:
    image: ${DOCKER_REGISTRY-}apigeteway
    build:
      context: .
      dockerfile: ApiGeteway/Dockerfile
    ports:
    - 9004:8080
    - 9005:8081
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_HTTPS_PORT=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=mypass123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
  